import { StyleSheet } from 'react-native';

const localStyles = StyleSheet.create({
  pageTitle: {
    fontSize: 28,
    fontWeight: '700',
    color: '#0F172A',
    marginTop: 16,
  },
  pageSubtitle: {
    fontSize: 14,
    color: '#64748B',
    marginTop: 6,
    marginBottom: 18,
  },
  tabBar: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  tabBarContent: {
    flexDirection: 'row',
  },
  tabItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderBottomWidth: 2.5,
    borderBottomColor: 'transparent',
  },
  tabItemActive: {
    backgroundColor: '#F8FAFC',
  },
  tabLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#94A3B8',
  },
  tabLabelActive: {
    fontWeight: '700',
  },
  tabHelper: {
    fontSize: 13,
    lineHeight: 18,
    color: '#64748B',
    marginTop: 10,
    marginBottom: 18,
  },
  sectionCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    padding: 18,
    marginBottom: 18,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 16,
  },
  sectionIconWrap: {
    width: 42,
    height: 42,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  sectionHeaderCopy: {
    flex: 1,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#0F172A',
  },
  sectionDescription: {
    fontSize: 13,
    lineHeight: 18,
    color: '#64748B',
    marginTop: 4,
  },
  statusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  settingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  settingCopy: {
    flex: 1,
    marginRight: 12,
  },
  settingDescription: {
    fontSize: 12,
    lineHeight: 18,
    color: '#64748B',
    marginTop: 4,
  },
  statusLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#334155',
  },
  statusChip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
  },
  statusChipEnabled: {
    backgroundColor: '#DCFCE7',
    borderColor: '#86EFAC',
  },
  statusChipDisabled: {
    backgroundColor: '#FEE2E2',
    borderColor: '#FCA5A5',
  },
  statusChipText: {
    fontSize: 13,
    fontWeight: '700',
    marginLeft: 6,
  },
  helperText: {
    fontSize: 13,
    color: '#64748B',
    marginBottom: 14,
  },
  emptyBox: {
    borderRadius: 14,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    padding: 14,
  },
  emptyTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#334155',
    marginBottom: 4,
  },
  emptyText: {
    fontSize: 13,
    lineHeight: 18,
    color: '#64748B',
  },
  printerList: {
    gap: 10,
  },
  printerItem: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    backgroundColor: '#F8FAFC',
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  printerItemActive: {
    borderColor: '#93C5FD',
    backgroundColor: '#EFF6FF',
  },
  printerCopy: {
    flex: 1,
    marginLeft: 12,
  },
  printerName: {
    fontSize: 14,
    fontWeight: '700',
    color: '#0F172A',
  },
  printerDevice: {
    fontSize: 12,
    color: '#64748B',
    marginTop: 2,
  },
  franchiseAddressGroupList: {
    gap: 12,
  },
  franchiseAddressGroup: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    backgroundColor: '#FFFFFF',
    padding: 14,
  },
  franchiseAddressGroupHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  franchiseAddressGroupBadge: {
    width: 38,
    height: 38,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ECFEFF',
    borderWidth: 1,
    borderColor: '#A5F3FC',
  },
  franchiseAddressGroupCopy: {
    flex: 1,
    marginLeft: 10,
  },
  franchiseAddressOptionList: {
    gap: 8,
  },
  franchiseAddressOption: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    backgroundColor: '#F8FAFC',
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  franchiseAddressOptionActive: {
    borderColor: '#99F6E4',
    backgroundColor: '#F0FDFA',
  },
  franchiseAddressOptionCopy: {
    flex: 1,
    marginLeft: 12,
  },
  primaryButton: {
    marginTop: 16,
    justifyContent: 'center',
  },
  secondaryButton: {
    marginTop: 10,
    justifyContent: 'center',
    backgroundColor: '#334155',
  },
  primaryButtonDisabled: {
    opacity: 0.6,
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontWeight: '700',
  },
  fieldBlock: {
    marginTop: 16,
  },
  fieldLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#334155',
    marginBottom: 6,
  },
  selectorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  selectorInput: {
    flex: 1,
    marginTop: 0,
  },
  selectorListButton: {
    minHeight: 48,
    paddingHorizontal: 14,
    borderRadius: 10,
    backgroundColor: '#334155',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  selectorListButtonText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '700',
    marginLeft: 6,
  },
  input: {
    minHeight: 48,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#CBD5E1',
    backgroundColor: '#F8FAFC',
    color: '#0F172A',
    paddingHorizontal: 14,
    paddingVertical: 10,
    marginTop: 6,
  },
  inputDisabled: {
    backgroundColor: '#F1F5F9',
    color: '#64748B',
  },
  multilineInput: {
    minHeight: 96,
    textAlignVertical: 'top',
  },
  profileRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
  },
  profileInput: {
    flex: 1,
    marginTop: 0,
  },
  profileInputSpacing: {
    marginLeft: 10,
  },
  removeProfileButton: {
    marginLeft: 10,
    padding: 4,
  },
  selectionModal: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    height: '88%',
    paddingBottom: 20,
  },
  selectionModalHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
  },
  selectionModalHeaderCopy: {
    flex: 1,
    marginRight: 12,
  },
  selectionModalTitle: {
    fontSize: 17,
    fontWeight: '800',
    color: '#0F172A',
  },
  selectionModalSubtitle: {
    fontSize: 12,
    lineHeight: 18,
    color: '#64748B',
    marginTop: 4,
  },
  selectionModalClose: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  selectionSearchWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 16,
    marginTop: 16,
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: '#F8FAFC',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  selectionSearchIcon: {
    marginRight: 8,
  },
  selectionSearchInput: {
    flex: 1,
    fontSize: 14,
    color: '#0F172A',
    padding: 0,
  },
  selectionModalList: {
    flex: 1,
    marginTop: 12,
  },
  selectionModalListContent: {
    paddingHorizontal: 16,
    paddingBottom: 8,
  },
  selectionModalItem: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    backgroundColor: '#F8FAFC',
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 10,
  },
  selectionModalItemActive: {
    borderColor: '#99F6E4',
    backgroundColor: '#F0FDFA',
  },
  selectionModalItemCopy: {
    flex: 1,
    marginLeft: 12,
  },
  selectionModalItemTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#0F172A',
  },
  selectionModalItemMeta: {
    fontSize: 12,
    lineHeight: 18,
    color: '#64748B',
    marginTop: 2,
  },
  searchEmptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
    paddingVertical: 36,
  },
  searchEmptyStateTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#334155',
    marginTop: 10,
    marginBottom: 4,
    textAlign: 'center',
  },
  searchEmptyStateText: {
    fontSize: 13,
    lineHeight: 18,
    color: '#64748B',
    textAlign: 'center',
    marginTop: 8,
  },
  sectionLoader: {
    marginTop: 18,
  },
});

export default localStyles;
